version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  configure_infrastructure: 
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout
        - add_ssh_keys:
                fingerprints: 3f:95:e1:43:6c:70:f6:6f:ec:ca:4b:55:e9:60:89:95
        - run:
            name: Install Ansible
            command: |
               sudo apt install --user ansible
        - run:
            name: Run PlayBook and configure server
            command: |
               ansible-playbook -i inventory main-remote.yml
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
     # - build
      - configure_infrastructure
